### ISSUE TITLE
issue in running dockerTask.sh: xdg-open

### ISSUE THREAD

**Issue by rpfigueira** [living-atlases/la-toolkit#4]
In Ubuntu 20.04 LTS, running `./dockerTas.sh compose`, fails with a message:
`Opening site......................../dockerTask.sh: line 104: xdg-open: command not found`
That command is provided by xdg-utils, which can be installed with the command:
`apt install xgd-utils`

**Comment by vjrj** [comment]
Thanks indeed @rpfigueira. Fixed in the README.

**Comment by vjrj** [comment]
Thanks again, if you have any other trouble please don't hesitate in add an issue or contact me in slack.
