### ISSUE TITLE
SSH gateway is not working for the first server

### ISSUE THREAD

**Issue by sylmorin-gbif** [living-atlases/la-toolkit#7]
Very strangely, we cannot use the SSH gateway for the FIRST server defined.

In the screenshot below, gateway (recol2) is used to connect to recol1. 

![image](https://user-images.githubusercontent.com/56630013/154502006-881805e8-f64f-4979-a6e4-38976b48b1de.png)

I had to re-create my configuration, starting by the VM recol2 and then recol1, because if recol1 was defined first, it wasn't saved (when you go back to this screen, the gateway part is empty)

**Comment by vjrj** [comment]
ahhhh, ok, yes, if the configuration is not saved, the gateway dropbox is empty, right?

**Comment by sylmorin-gbif** [comment]
![Peek 2022-02-17 19-04](https://user-images.githubusercontent.com/56630013/154543357-0bbe658f-36c2-4b5e-a1c2-23573e74aebd.gif)

**Comment by sylmorin-gbif** [comment]
It only happens for the FIRST server of the list ! 
That's why I had to invert them during the servers creation, to have my "recol1" server in the 2nd place of the list...
